---
all:
  hosts:
    elastic-instance:
      ansible_host: 51.250.13.180
    kibana-instance:
      ansible_host: 51.250.5.174
    filebeat-instance:
      ansible_host: 51.250.11.88
  vars:
    ansible_connection: ssh
    ansible_user: eugene
    ansible_private_key_file: /home/eugene/.ssh/id_rsa

elasticsearch:
  hosts:
    elastic-instance:

kibana:
  hosts:
    kibana-instance:

filebeat:
  hosts:
    filebeat-instance: