---
all:
  hosts:
    elastic-instance:
      ansible_host: 51.250.9.175
    kibana-instance:
      ansible_host: 51.250.8.194
    filebeat-instance:
      ansible_host: 51.250.5.192
  vars:
    ansible_connection: ssh
    ansible_user: eugene
    ansible_private_key_file: /home/eugene/.ssh/id_rsa
    elk_stack_version: "7.17.0"

elasticsearch:
  hosts:
    elastic-instance:

kibana:
  hosts:
    kibana-instance:

filebeat:
  hosts:
    filebeat-instance: