---
  - src: git@github.com:netology-code/mnt-homeworks-ansible.git
    scm: git
    version: "2.1.4"
    name: elastic
  - src: git@github.com:kamaok/ansible-netology-task-4-kibana-role.git
    scm: git
    version: "0.0.1"
    name: kibana-role
  - src: git@github.com:kamaok/ansible-netology-task-4-filebeat-role.git
    scm: git
    version: "0.0.1"
    name: filebeat-role